### ISSUE TITLE
SafeFrame property in YAML being ignored by GAM

### ISSUE THREAD

**Issue by timbolimboslice** [prebid/line-item-manager#119]
* line-item-manager version: 0.2.9
* Python version: 3.9
* Operating System: macOS Monterey, 12.6

### Description
I'm trying to create line items with creatives that do not serve in a SafeFrame. I'm setting the `safe_frame` under `creative` > `banner` to false. When I do a test run, the creatives that are created still have "Serve into a SafeFrame" checked off. 

### What I Did
I ran this command with the attached YAML file: `line_item_manager create txmo_config-updated.yml -b teads -t`

[YAML File](https://github.com/prebid/line-item-manager/files/9788275/txmo_config-updated.txt)

[GAM Screenshot](https://user-images.githubusercontent.com/11657201/195895889-b5b0bde9-0eda-4816-8a40-1803892dc267.png)

**Comment by torontobros** [comment]
Hey Tim

Yank files are case sensitive and used input a lower case “false” as value

Cheers
Dan

**Comment by timbolimboslice** [comment]
I did try both "false" and "False" with the same results.

**Comment by torontobros** [comment]
I ran your yaml file on my machine and it worked ok with Safeframe unchecked. Are you sure you're inspecting the correct creative?

**Comment by dshore** [comment]
FYI, false or False are interpreted the same by python PyYAML package used by the tool

**Comment by Egge7** [comment]
I just ran into the same issue. I know its been a while, has somebody found a fix for this?

**Comment by Egge7** [comment]
NVM, I found my issue and I would suspect that this is acutally what caused the problem for @timbolimboslice as well. If there already is a creative mathing name or ID in your config file, it will use that creative for all line items (if there already is a creative present that has SafeFrame turned on, this script will not replace or update that creative).

Easy fix: Change the creative name to create a new one
