### ISSUE TITLE
Error: Check your private key file. Not able to successfully access your service account

### ISSUE THREAD

**Issue by diecastben** [prebid/line-item-manager#152]
Hi, I'm experiencing the same issue as this [issue ](https://github.com/prebid/line-item-manager/issues/113)describes.

I ran a few successful line item manager "jobs" and suddenly this error started to show without any change from my end to the configuration or service key JSON files.

This is the prompt I use:
`line_item_manager create someName.yml --network-code 2161****323 -k C:\Users\b.f\someName.json --single-order`

I'm using line item manager version 0.2.12
with version Python 3.9.10
with version pip 22.3.1

The authentication details are 100% correct.
and yet I all of a sudden started to repeatedly receive the following error:
Error: Check your private key file. Not able to successfully access your service account

**Comment by dshore** [comment]
@diecastben Sorry I am not able to reproduce the problem you are seeing.  Can you run again with the '-v' verbose option, and post output here. This might help us see a detailed error message from maybe googleads?
