### ISSUE TITLE
Geo Location Targeting Error

### ISSUE THREAD

**Issue by soman** [prebid/line-item-manager#154]
* line-item-manager version: 0.2.12
* Python version:  3.7.9
* Operating System: Windows 11

### Description

I am getting errors related to geolocation targeting. I've attached two screenshots.

### What I Did

```
line_item_manager create -n test_config.yml --single-order
![lim-error-1](https://github.com/prebid/line-item-manager/assets/2465685/23c552de-f440-4c6b-bcf3-29ebc0bc3dbe)
![lim-error-2](https://github.com/prebid/line-item-manager/assets/2465685/04ae392c-511e-4b53-8d83-8974288a9099)

```

**Comment by dshore** [comment]
@soman Looks like you are missing a hyphen in front of name that would indicate in yaml that the custom block is an array:
You want this:
```
  custom: # list (optional)
    - name: "country"
```
Not what I think you have as this:
```
  custom: # list (optional)
    name: "country"
```
