### ISSUE TITLE
Deployment of version 0.2.13 has failed

### ISSUE THREAD

**Issue by kmrnpu** [prebid/line-item-manager#164]
* line-item-manager version: 0.2.13

### Description
I noticed that the deployment of version 0.2.13 has failed due to authentication failure.

https://github.com/prebid/line-item-manager/actions/runs/10625259515/job/29480482464

**Comment by dshore** [comment]
Thank you, yes this is a known issue that is in progress to resolve.  PyPI changed there auth and currently access to the account is limited and I was not able to update the credentials.  This hopefully will be resolved soon.

**Comment by dshore** [comment]
closing this
