### ISSUE TITLE
Creative for Bidder specific line items needs the biddercode in the pattern match macro replaced by actual bidder code

### ISSUE THREAD

**Issue by stygianmessiah** [prebid/line-item-manager#2]
* line-item-manager version: 0.1.8

### Description

When creating a bidder based set of line items, the creative used is this:
`<script src = "https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js"></script>
    <script>
      var ucTagData = {};
      ucTagData.adServerDomain = "";
      ucTagData.pubUrl = "%%PATTERN:url%%";
      ucTagData.adId = "%%PATTERN:hb_adid_BIDDERCODE%%";
      ucTagData.cacheHost = "%%PATTERN:hb_cache_host_BIDDERCODE%%";
      ucTagData.cachePath = "%%PATTERN:hb_cache_path_BIDDERCODE%%";
      ucTagData.uuid = "%%PATTERN:hb_cache_id_BIDDERCODE%%";
      ucTagData.mediaType = "%%PATTERN:hb_format_BIDDERCODE%%";
      ucTagData.env = "%%PATTERN:hb_env%%";
      ucTagData.size = "%%PATTERN:hb_size_BIDDERCODE%%";
      ucTagData.hbPb = "%%PATTERN:hb_pb_BIDDERCODE%%";
      // mobileResize needed for mobile GAM only
      ucTagData.mobileResize = "hb_size:%%PATTERN:hb_size_BIDDERCODE%%";
      try {
        ucTag.renderAd(document, ucTagData);
      } catch (e) {
        console.log(e);
      }
    </script>`

The `BIDDERCODE` in the above code should be replaced by the actual bidder specified when running the command with the `-b` modifier.

### Here's what the tool creates

![image](https://user-images.githubusercontent.com/35668134/101806097-8d715700-3ae1-11eb-9bdb-4bc62ec006e0.png)

### Here's what the tool should create
![image](https://user-images.githubusercontent.com/35668134/101806294-c8738a80-3ae1-11eb-91c8-a837c866d9dd.png)

**NOTE:** GAM has an upper limit of 20 characters for each key you send to it. For some bidders the entire key including the `hb_pb_` or `hb_cache_host_`, may exceed the 20 char limit, so it should correctly truncate the length.

For example, if we choose bidder `rubicon` it would be `hb_cache_host_rubico`

**Comment by dshore** [comment]
Templating is supported as follows, but do to a bux w/ multi-line template strings you must upgrade to at least version 0.1.9:

`    
creative: # at least one of the following types is required {video, banner}
  name: "Prebid {{ bidder_name }}-{{ media_type }}"
  banner:
    sizes: # list
      - height: 480
        width: 640
    snippet: |
      <script src = "https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js"></script>
      <script>
        var ucTagData = {};
        ucTagData.adServerDomain = "";
        ucTagData.pubUrl = "%%PATTERN:url%%";
        ucTagData.adId = "%%PATTERN:{{ hb_adid }}%%";
        ucTagData.cacheHost = "%%PATTERN:{{ hb_cache_host }}%%";
        ucTagData.cachePath = "%%PATTERN:{{ hb_cache_path }}%%";
        ucTagData.uuid = "%%PATTERN:{{ hb_cache_id }}%%";
        ucTagData.mediaType = "%%PATTERN:{{ hb_format }}%%";
        ucTagData.env = "%%PATTERN:hb_env%%";
        ucTagData.size = "%%PATTERN:{{ hb_size }}%%";
        ucTagData.hbPb = "%%PATTERN:{{ hb_pb }}%%";
        ucTagData.mobileResize = "hb_size:%%PATTERN:{{ hb_size }}%%";
        try {
          ucTag.renderAd(document, ucTagData);
        } catch (e) {
          console.log(e);
        }
      </script>
`
