### ISSUE TITLE
Option to remove existing line items

### ISSUE THREAD

**Issue by Winterborne** [prebid/line-item-manager#21]
Sometimes it becomes important to remove line items one already has set up for a bidder. A bidder might not be generating enough be producing enough demand to justify its place in the stack, or start exhibiting payment problems. Or you might decide you want to rework their line items, perhaps changing the size of the increments between each item.

It would be great for the tool to offer a command to remove existing line items. If done right, this could both speed up the line item removal process, and provide some double-checks to make sure the correct line items are being removed.

Thank you for the tool!

**Comment by stygianmessiah** [comment]
Hi @Winterborne,

Thanks for this suggestion. When you say "remove" do you mean deleting line items or just archiving them? Once a line item starts delivering it cannot be deleted, but it can be archived.

The reasoning for not including this by default, was that archiving means those line items stop being active and it could potentially cause the publisher to lose revenue if not done correctly. Hence, it must be done very carefully. However, it is a good feature and can make line item management more efficient.

**Comment by Winterborne** [comment]
I mean "archive" in this case, for the reason you cite.

**Comment by dshore** [comment]
I do not think this would be difficult to implement.  But does feel like a new category of operations requiring a new subcommand, something like:

`line_item_manager archive ...`

Any suggestions on specifying what we would archive, e.g. by line item id, order id, names??

**Comment by dshore** [comment]
@Winterborne any thoughts on above?  Specifying what to archive?

**Comment by dshore** [comment]
See: examples/bin/archive_order.py

Try:
`python examples/bin/archive_order.py -h`

**Comment by dshore** [comment]
Released with: v0.1.15
