### ISSUE TITLE
Multiple creatives

### ISSUE THREAD

**Issue by frjohan** [prebid/line-item-manager#24]
* line-item-manager version: 0.1.14

### Question

How do i create multiple banner creatives to each line item?

**Comment by dshore** [comment]
Hey @frjohan,  The CLI tool supports implementation of the steps outlined here:

[How to simplify line item setup](https://docs.prebid.org/overview/how-to-simplify-line-item-setup.html)

In short creatives are added as a list of sizes, see creative.banner.sizes in this config:

[Tool Base Config](https://github.com/prebid/line-item-manager/blob/master/line_item_manager/conf.d/line_item_manager.yml
)

Hope this helps!
