### ISSUE TITLE
Adding a -v modifier for line_item_manager command for the version of the tool

### ISSUE THREAD

**Issue by stygianmessiah** [prebid/line-item-manager#4]
* line-item-manager version: 0.1.10
* Python version:
* Operating System:

### Description

I'd like to be able to see what version of the tool I have installed on my computer using the **-v** modifier

The command should be `$ line_item_manager -v`

**Comment by dshore** [comment]
I think this should be implemented as '--version' to avoid confusion with the subcommand create option of "-v, --verbose".

**Comment by dshore** [comment]
Dependent on 0.1.11
