### ISSUE TITLE
Custom targeting hb_bidder contains all key-values

### ISSUE THREAD

**Issue by martinsvoboda** [prebid/line-item-manager#43]
* line-item-manager version: 0.2.1
* Python version: 3.9.1
* Operating System: MacOs

### Description
I want to use single order approach for all bidders except Teads (because Teads do not support SafeFrame, I create separated order for them).

Inside config targeting set:

```
targeting:
  custom:
    - name: "hb_bidder"
      operator: "IS_NOT"
      values:
        - "teads"
```

But line items are created with targeting `hb_bidder is none of sovrn, teads, appnexus`. Basically it contains all values defined for hb_bidder key-value. Note: Some time ago I manually set hb_bidder for testing purposes. Seems that used operator or key-value type doesn't affect anything.

Targeting for created line item:
![Screenshot 2021-03-04 at 12 45 28](https://user-images.githubusercontent.com/558139/109959257-84121800-7ce7-11eb-8997-a5541a6d806f.png)

Key-value settings:
![Screenshot 2021-03-04 at 12 46 45](https://user-images.githubusercontent.com/558139/109959415-bcb1f180-7ce7-11eb-8c05-c8034c93a1f3.png)

### What I Did

```
line_item_manager create gam_universal_config.yml --single-order --test-run --private-key-file secrets/xxxx.json

YML config:

publisher:
  network_code: 1234
  network_name: "XXX"
advertiser:
  name: "Prebid"
creative:
  name: "prebid-{{ media_type }}"
  banner:
    sizes:
      - width: 200
        height: 200
      - width: 250
        height: 250
    snippet: |
      <script src = "https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js"></script>
      <script>
        var ucTagData = {};
        ucTagData.adServerDomain = "";
        ucTagData.pubUrl = "%%PATTERN:url%%";
        ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;
        ucTagData.hbPb = "%%PATTERN:hb_pb%%";

        try {
          ucTag.renderAd(document, ucTagData);
        } catch (e) {
          console.log(e);
        }
      </script>
order:
  name: "Prebid-{{ media_type }}-{{ time }} {{ cpm_min }}-{{ cpm_max }}"
line_item:
  name: "Prebid-{{ media_type }} @ {{ cpm }}"
  item_type: "price_priority"
targeting:
  custom: # list (optional)
    - name: "hb_bidder"
      operator: "IS_NOT" # optional: defaults to "IS"
      values:
        - "teads"
rate:
  currency: "CZK" # required
  granularity:
    type: "custom" # required, choices: "low", "med", "high", "auto", "dense", "custom"
    custom: # optional, requires type "custom" above
      - min: 0.10
        max: 135.00
        interval: 0.10


```

**Comment by dshore** [comment]
This is indeed a bug, good catch!  But I think it should be addressed here:
https://github.com/prebid/line-item-manager/blob/master/line_item_manager/gam_operations.py#L57

In this case other previous set key-values are being returned from the fetch and not filtered from the returned result set.  Then this results in them included here:

**Comment by dshore** [comment]
I am changing my opinion, I think below is what you want when you do a fetch and add records:
https://github.com/prebid/line-item-manager/blob/master/line_item_manager/gam_operations.py#L57

So I agree this should be fixed in this file:
https://github.com/prebid/line-item-manager/blob/master/line_item_manager/gam_config.py

**Comment by dshore** [comment]
I think this addresses it:
https://github.com/prebid/line-item-manager/pull/47
