### ISSUE TITLE
WARNING:googleads.common:Your default encoding, cp1252, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors.

### ISSUE THREAD

**Issue by murattyilmaz** [prebid/line-item-manager#76]
* line-item-manager version: 0.2.3
* Python version: 3.9
* Operating System: Windows 10 Pro

### Description

I'm trying to create line items with adunits but line item manager warns me with this message.
WARNING:googleads.common:Your default encoding, cp1252, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors.

I found that my adunit names contains Turkish characters like "mysite_Desktop_**İç**erikAras**ı**_Top" and warning comes from googleads sdk but there is no way to change default encoding to UTF-8. 

I think it will be fixed if you guys use UTF-8 as default encoding. I've also searched codes abut couldn't find  where should I add this.

### What I Did

My execution command is;
 line_item_manager create mysite.yml -b criteo -k "Avva Mobile - Header Bidding - Service Account.json" --dry-run

**Comment by dshore** [comment]
@murattyilmaz I am not able to reproduce this error.  It is my understanding that some of those characters you chose can not be encoded in cp1252: e.g. İ ı

I would suggest your configuration input file be in something that can be decoded as 'utf-8'.

If you provide a configuration file and how it is encoded, I might be of more assistance.
