### ISSUE TITLE
Resume interrupted operation of line items creation

### ISSUE THREAD

**Issue by Zer0Divis0r** [prebid/line-item-manager#78]
* line-item-manager version: 0.2.3
* Python version: 3.9.7
* Operating System: Red Hat

I am wondering if line item manager is supposed to resume line items creation, or should I always start from the scratch when the process got interrupted.

As far as I see it can detect presense of advertiser, creatives and orders, and it is logical for the line itme manager to also see that line items already exist in the order (they have the same name), but instead it fails with `UniqueError.NOT_UNIQUE` . My name template for line items is `Prebid @{{cpm}}`. 
Since I do 450 line items per order, it also fails with `EntityChildrenLimitReachedError.LINE_ITEM_LIMIT_FOR_ORDER_REACHED` when I simly re-run the same command with a different name template.

Thanks.

**Comment by dshore** [comment]
@Zer0Divis0r Can you please attach your complete config yaml file?

**Comment by dshore** [comment]
My bad.  I errantly referenced this issue in the commit message.
