### ISSUE TITLE
Support for more line item types

### ISSUE THREAD

**Issue by milesmahon** [prebid/line-item-manager#86]
Currently, the tool only supports [price_priority and standard](https://github.com/prebid/line-item-manager/blob/master/line_item_manager/conf.d/schema.yml#L92-L95) line items. 

We would like to be able to create line items with sponsorship priority. This is supported by the [GAM API](https://developers.google.com/ad-manager/api/reference/v202111/LineItemService.LineItemType).

**Comment by milesmahon** [comment]
Just documenting progress: if we allow sponsorship priority line items, we get the error ReservationDetailsError.UNLIMITED_UNITS_BOUGHT_NOT_ALLOWED @ lineItem[23].primaryGoal.units; looking into how to specify this primaryGoal units value. The error code suggests as well that specifying a duration might fix this, if that doesn't work.

**Comment by dshore** [comment]
@milesmahon This is available as a dev release:
```
$ pip uninstall line-item-manager
$ pip install https://github.com/prebid/line-item-manager/archive/master.zip
$ line_item_manager --version
line-item-manager version 0.2.4-dev1
```
